package com.putao.wd.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.putao.wd.db.entity.AddressDB;

import com.putao.wd.db.dao.AddressDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressDBDaoConfig;

    private final AddressDBDao addressDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressDBDaoConfig = daoConfigMap.get(AddressDBDao.class).clone();
        addressDBDaoConfig.initIdentityScope(type);

        addressDBDao = new AddressDBDao(addressDBDaoConfig, this);

        registerDao(AddressDB.class, addressDBDao);
    }
    
    public void clear() {
        addressDBDaoConfig.getIdentityScope().clear();
    }

    public AddressDBDao getAddressDBDao() {
        return addressDBDao;
    }

}
