package com.putao.wd.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.putao.wd.db.entity.ShippingAddressDB;

import com.putao.wd.db.dao.ShippingAddressDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shippingAddressDBDaoConfig;

    private final ShippingAddressDBDao shippingAddressDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shippingAddressDBDaoConfig = daoConfigMap.get(ShippingAddressDBDao.class).clone();
        shippingAddressDBDaoConfig.initIdentityScope(type);

        shippingAddressDBDao = new ShippingAddressDBDao(shippingAddressDBDaoConfig, this);

        registerDao(ShippingAddressDB.class, shippingAddressDBDao);
    }
    
    public void clear() {
        shippingAddressDBDaoConfig.getIdentityScope().clear();
    }

    public ShippingAddressDBDao getShippingAddressDBDao() {
        return shippingAddressDBDao;
    }

}
