package com.putao.wd.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.putao.wd.db.entity.ShippingAddressDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "putao_wd_shipping_address".
*/
public class ShippingAddressDBDao extends AbstractDao<ShippingAddressDB, Long> {

    public static final String TABLENAME = "putao_wd_shipping_address";

    /**
     * Properties of entity ShippingAddressDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Province = new Property(2, String.class, "province", false, "PROVINCE");
        public final static Property City = new Property(3, String.class, "city", false, "CITY");
        public final static Property District = new Property(4, String.class, "district", false, "DISTRICT");
        public final static Property Street = new Property(5, String.class, "street", false, "STREET");
        public final static Property Mobile = new Property(6, String.class, "mobile", false, "MOBILE");
        public final static Property IsDefault = new Property(7, Boolean.class, "isDefault", false, "IS_DEFAULT");
    };


    public ShippingAddressDBDao(DaoConfig config) {
        super(config);
    }
    
    public ShippingAddressDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"putao_wd_shipping_address\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"PROVINCE\" TEXT NOT NULL ," + // 2: province
                "\"CITY\" TEXT NOT NULL ," + // 3: city
                "\"DISTRICT\" TEXT NOT NULL ," + // 4: district
                "\"STREET\" TEXT NOT NULL ," + // 5: street
                "\"MOBILE\" TEXT NOT NULL ," + // 6: mobile
                "\"IS_DEFAULT\" INTEGER);"); // 7: isDefault
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_putao_wd_shipping_address__id ON putao_wd_shipping_address" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"putao_wd_shipping_address\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ShippingAddressDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getProvince());
        stmt.bindString(4, entity.getCity());
        stmt.bindString(5, entity.getDistrict());
        stmt.bindString(6, entity.getStreet());
        stmt.bindString(7, entity.getMobile());
 
        Boolean isDefault = entity.getIsDefault();
        if (isDefault != null) {
            stmt.bindLong(8, isDefault ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ShippingAddressDB readEntity(Cursor cursor, int offset) {
        ShippingAddressDB entity = new ShippingAddressDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // province
            cursor.getString(offset + 3), // city
            cursor.getString(offset + 4), // district
            cursor.getString(offset + 5), // street
            cursor.getString(offset + 6), // mobile
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // isDefault
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ShippingAddressDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setProvince(cursor.getString(offset + 2));
        entity.setCity(cursor.getString(offset + 3));
        entity.setDistrict(cursor.getString(offset + 4));
        entity.setStreet(cursor.getString(offset + 5));
        entity.setMobile(cursor.getString(offset + 6));
        entity.setIsDefault(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ShippingAddressDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ShippingAddressDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
