/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_putao_GPush
#define _Included_com_putao_GPush
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint Java_com_putao_ptx_push_core_GPush_initial(JNIEnv* env,
                                                    jobject thiz,
                                                    jstring jhttp_url,
                                                    jstring jplatform,
                                                    jstring jdevice_token);

JNIEXPORT jint Java_com_putao_ptx_push_core_GPush_login(JNIEnv* env,
                                                    jobject thiz,
                                                    jstring jsecret_key,
                                                    jstring jsecret_token);

JNIEXPORT jint Java_com_putao_ptx_push_core_GPush_reg(JNIEnv* env, jobject thiz, jstring jappId);

JNIEXPORT jint Java_com_putao_ptx_push_core_GPush_unreg(JNIEnv* env, jobject thiz, jstring jappId);

JNIEXPORT jint Java_com_putao_ptx_push_core_GPush_uninitial(JNIEnv* env, jobject thiz);


#ifdef __cplusplus
}
#endif
#endif
