package com.putao.wd.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.sunnybear.library.model.db.DBEntity;

/**
 * Entity mapped to table "putao_wd_shipping_address".
 */
public class AddressDB extends DBEntity {

    private Long id;
    /**
     * Not-null value.
     */
    private String name;
    /**
     * Not-null value.
     */
    private String province;
    /**
     * Not-null value.
     */
    private String city;
    /**
     * Not-null value.
     */
    private String district;
    /**
     * Not-null value.
     */
    private String street;
    /**
     * Not-null value.
     */
    private String mobile;
    private Boolean isDefault;

    public AddressDB() {
    }

    public AddressDB(Long id) {
        this.id = id;
    }

    public AddressDB(Long id, String name, String province, String city, String district, String street, String mobile, Boolean isDefault) {
        this.id = id;
        this.name = name;
        this.province = province;
        this.city = city;
        this.district = district;
        this.street = street;
        this.mobile = mobile;
        this.isDefault = isDefault;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Not-null value.
     */
    public String getProvince() {
        return province;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * Not-null value.
     */
    public String getCity() {
        return city;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Not-null value.
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * Not-null value.
     */
    public String getStreet() {
        return street;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Not-null value.
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Boolean getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

}
