package com.putao.wd.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.sunnybear.library.model.db.DBEntity;

/**
 * Entity mapped to table "putao_wd_city".
 */
public class CompanionDB extends DBEntity {

    private String id;
    private String type;
    private String release_time;
    private String content_lists;
    private String isDownload;

    public CompanionDB(String id, String type, String release_time, String content_lists, String isDownload) {
        this.id = id;
        this.type = type;
        this.release_time = release_time;
        this.content_lists = content_lists;
        this.isDownload = isDownload;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRelease_time() {
        return release_time;
    }

    public void setRelease_time(String release_time) {
        this.release_time = release_time;
    }

    public String getContent_lists() {
        return content_lists;
    }

    public void setContent_lists(String content_lists) {
        this.content_lists = content_lists;
    }

    public String getIsDownload() {
        return isDownload;
    }

    public void setIsDownload(String isDownload) {
        this.isDownload = isDownload;
    }
}
