package com.putao.wd.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.sunnybear.library.model.db.DBEntity;

/**
 * Entity mapped to table "putao_wd_province".
 */
public class ProvinceDB extends DBEntity {

    private String province_id;
    private String name;

    public ProvinceDB() {
    }

    public ProvinceDB(String province_id) {
        this.province_id = province_id;
    }

    public ProvinceDB(String province_id, String name) {
        this.province_id = province_id;
        this.name = name;
    }

    public String getProvince_id() {
        return province_id;
    }

    public void setProvince_id(String province_id) {
        this.province_id = province_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
